# Generated by Django 4.1.3 on 2022-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtoServico', '0001_initial'),
        ('produto', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='produtoServico.ProdutoServico', to='produto.produto'),
        ),
    ]
