# Generated by Django 4.1.2 on 2022-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
