# Generated by Django 4.1.2 on 2022-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-horario'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
